### PR TITLE
Add instance group support to NGINX container builder

### PR DESCRIPTION
**Pull request by kushal1093**
## Description:
Add ENV_CONTROLLER_INSTANCE_GROUP variable to support instance group. 

## Reviewers:
@brianehlert @1996sajal @framer777

### CODE REVIEW

**Comment by brianehlert** [comment]
This should be an 'instance_group' just like the API and GUI - not truncated to 'group'
That will make it easier to drop the 'controller' portion of the env var at some point in the future.

**Comment by framer777** [comment]
LGTM, please update PR description to reflect the latest var name

@1996sajal please test and merge

**Review by 1996sajal — APPROVED** [review]

**Comment by 1996sajal** [comment]
@kushal1093, there should be readme changes for the same flag which is added here. But I don't see this MR or any other having those.

**Comment by 1996sajal** [comment]
Screenshot 2021-03-25 at 19 13 30

**Comment by kushal1093** [comment]
> @kushal1093, there should be readme changes for the same flag which is added here. But I don't see this MR or any other having those.
> 
> Ccing:- @brianehlert @framer777

As for documenting the variable in the README, the variable is of no use unless DPM is merged to Master on the controller. Maybe we can document it once it is merged? 

Thoughts?
@brianehlert  @framer777

**Comment by richbrowne** [comment]
@kushal1093 Please update the pull request to rename from CONTROLLER_GROUP to CONTROLLER_INSTANCE_GROUP.  Let's align with instance name.  Otherwise, we might confuse people who think about cgroups and containerization.

**Comment by kushal1093** [comment]
> @kushal1093 Please update the pull request to rename from CONTROLLER_GROUP to CONTROLLER_INSTANCE_GROUP. Let's align with instance name. Otherwise, we might confuse people who think about cgroups and containerization.

Yes, it is done. The env variable name is `ENV_CONTROLLER_INSTANCE_GROUP`.

**Review by brianehlert — APPROVED** [review]

**Pull request merged**
